# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
(bold green)$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
${custom.yadm}\
$line_break\
$golang\
$nodejs\
$aws\
$cmd_duration\
$jobs\
$line_break\
[->](bold green) """

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[nodejs]
symbol = ''

[aws]
format = '$symbol($profile )(\[$duration\] )'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = '([\[$deleted$renamed$modified$typechanged$staged$untracked$ahead_behind\]]($style) )'

[custom.yadm]
command = 'yadm status --porcelain | wc -l'
when = 'yadm status | grep -q "Changes not staged for commit:\|Changes to be committed:"'
style = "yellow bold"
format = '[dotfiles:\((±$output)\)]($style)'
